/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: score_message.proto */

#ifndef PROTOBUF_C_score_5fmessage_2eproto__INCLUDED
#define PROTOBUF_C_score_5fmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ScoreUpdate ScoreUpdate;


/* --- enums --- */


/* --- messages --- */

struct  _ScoreUpdate
{
  ProtobufCMessage base;
  /*
   * Current players in the game
   */
  char *current_players;
  /*
   * Scores of the players
   */
  size_t n_scores;
  uint32_t *scores;
};
#define SCORE_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&score_update__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


/* ScoreUpdate methods */
void   score_update__init
                     (ScoreUpdate         *message);
size_t score_update__get_packed_size
                     (const ScoreUpdate   *message);
size_t score_update__pack
                     (const ScoreUpdate   *message,
                      uint8_t             *out);
size_t score_update__pack_to_buffer
                     (const ScoreUpdate   *message,
                      ProtobufCBuffer     *buffer);
ScoreUpdate *
       score_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   score_update__free_unpacked
                     (ScoreUpdate *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ScoreUpdate_Closure)
                 (const ScoreUpdate *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor score_update__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_score_5fmessage_2eproto__INCLUDED */
