/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: score_message.proto */

#ifndef PROTOBUF_C_score_5fmessage_2eproto__INCLUDED
#define PROTOBUF_C_score_5fmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _DisplayUpdateMessage DisplayUpdateMessage;


/* --- enums --- */


/* --- messages --- */

struct  _DisplayUpdateMessage
{
  ProtobufCMessage base;
  /*
   * Indicates if the server is shutting down
   */
  protobuf_c_boolean server_shutdown;
  /*
   * Indicates if the game is over
   */
  protobuf_c_boolean game_over;
  /*
   * 20x20 grid, represented as an array of strings
   */
  size_t n_grid;
  char **grid;
  /*
   * Array of scores for 8 players
   */
  size_t n_scores;
  uint32_t *scores;
  /*
   * String containing current players' names (max 8 chars)
   */
  char *current_players;
};
#define DISPLAY_UPDATE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&display_update_message__descriptor) \
    , 0, 0, 0,NULL, 0,NULL, (char *)protobuf_c_empty_string }


/* DisplayUpdateMessage methods */
void   display_update_message__init
                     (DisplayUpdateMessage         *message);
size_t display_update_message__get_packed_size
                     (const DisplayUpdateMessage   *message);
size_t display_update_message__pack
                     (const DisplayUpdateMessage   *message,
                      uint8_t             *out);
size_t display_update_message__pack_to_buffer
                     (const DisplayUpdateMessage   *message,
                      ProtobufCBuffer     *buffer);
DisplayUpdateMessage *
       display_update_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   display_update_message__free_unpacked
                     (DisplayUpdateMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DisplayUpdateMessage_Closure)
                 (const DisplayUpdateMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor display_update_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_score_5fmessage_2eproto__INCLUDED */
