/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: score_message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "score_message.pb-c.h"
void   display_update_message__init
                     (DisplayUpdateMessage         *message)
{
  static const DisplayUpdateMessage init_value = DISPLAY_UPDATE_MESSAGE__INIT;
  *message = init_value;
}
size_t display_update_message__get_packed_size
                     (const DisplayUpdateMessage *message)
{
  assert(message->base.descriptor == &display_update_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t display_update_message__pack
                     (const DisplayUpdateMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &display_update_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t display_update_message__pack_to_buffer
                     (const DisplayUpdateMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &display_update_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DisplayUpdateMessage *
       display_update_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DisplayUpdateMessage *)
     protobuf_c_message_unpack (&display_update_message__descriptor,
                                allocator, len, data);
}
void   display_update_message__free_unpacked
                     (DisplayUpdateMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &display_update_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor display_update_message__field_descriptors[5] =
{
  {
    "server_shutdown",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DisplayUpdateMessage, server_shutdown),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_over",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DisplayUpdateMessage, game_over),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "grid",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DisplayUpdateMessage, n_grid),
    offsetof(DisplayUpdateMessage, grid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scores",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DisplayUpdateMessage, n_scores),
    offsetof(DisplayUpdateMessage, scores),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_players",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DisplayUpdateMessage, current_players),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned display_update_message__field_indices_by_name[] = {
  4,   /* field[4] = current_players */
  1,   /* field[1] = game_over */
  2,   /* field[2] = grid */
  3,   /* field[3] = scores */
  0,   /* field[0] = server_shutdown */
};
static const ProtobufCIntRange display_update_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor display_update_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DisplayUpdateMessage",
  "DisplayUpdateMessage",
  "DisplayUpdateMessage",
  "",
  sizeof(DisplayUpdateMessage),
  5,
  display_update_message__field_descriptors,
  display_update_message__field_indices_by_name,
  1,  display_update_message__number_ranges,
  (ProtobufCMessageInit) display_update_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
