# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: score_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='score_message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13score_message.proto\"y\n\x14\x44isplayUpdateMessage\x12\x17\n\x0fserver_shutdown\x18\x01 \x01(\x08\x12\x11\n\tgame_over\x18\x02 \x01(\x08\x12\x0c\n\x04grid\x18\x03 \x03(\t\x12\x0e\n\x06scores\x18\x04 \x03(\r\x12\x17\n\x0f\x63urrent_players\x18\x05 \x01(\tb\x06proto3'
)




_DISPLAYUPDATEMESSAGE = _descriptor.Descriptor(
  name='DisplayUpdateMessage',
  full_name='DisplayUpdateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_shutdown', full_name='DisplayUpdateMessage.server_shutdown', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_over', full_name='DisplayUpdateMessage.game_over', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grid', full_name='DisplayUpdateMessage.grid', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scores', full_name='DisplayUpdateMessage.scores', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_players', full_name='DisplayUpdateMessage.current_players', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['DisplayUpdateMessage'] = _DISPLAYUPDATEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DisplayUpdateMessage = _reflection.GeneratedProtocolMessageType('DisplayUpdateMessage', (_message.Message,), {
  'DESCRIPTOR' : _DISPLAYUPDATEMESSAGE,
  '__module__' : 'score_message_pb2'
  # @@protoc_insertion_point(class_scope:DisplayUpdateMessage)
  })
_sym_db.RegisterMessage(DisplayUpdateMessage)


# @@protoc_insertion_point(module_scope)
